name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    #caches all dependencies so you don't have to redownload/recompile everything from scratch
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0

    - name: Version of Rust and Cargo
      run: rustc --version && cargo --version
             
    - name: Install cargo-deb
      uses: actions-rs/cargo@v1.0.1
      with: 
        command: install
        args: cargo-deb
      
    - name: Build
      run: cargo build --locked --release --all -v
      
    - name: Package as deb file
      uses: actions-rs/cargo@v1.0.1
      with:
        command: deb
        args: --no-build -v          
      
    # add the prysia.deb file to the apt repo which is part of
    # the github website repo
    - uses: sbtaylor15/apt-repo-action@v2.0.4
      # Only when we push on the main repository should we upload the results
      if: github.repository_owner == 'pyrsia' && github.event_name == 'push'
      with:
        github_token: ${{ secrets.APT }}
        repo_supported_version: |
          bionic
        repo_supported_arch: |
          amd64
        page_branch: gh-pages
        file: /home/runner/work/synapse/synapse/target/debian/synapse-bt_1.0.0_amd64.deb
        file_target_version: bionic
        public_key: ${{ secrets.GPG_PUBLIC }}
        private_key: ${{ secrets.GPG_PRIVATE }}
        key_passphrase: ${{ secrets.GPG_SECRET }}
        github_repository: pyrsia/pyrisa.github.io
